# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
  - name: People
    weight: 20
  - name: Advisor
    parent: People
    url: advisor
    weight: 21
  - name: The Group
    parent: People
    url: team
    weight: 22
  - name: Publications
    url: publication
    weight: 30
  - name: News
    url: post
    weight: 40
  - name: Events
    url: event
    weight: 45
  - name: Contact
    url: contact
    weight: 50
